version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
environment:
    matrix:
    - solution_folder: /VS/News_Table/News_Table
      full_project_name: /VS/News_Table/News_Table/News_Table.csproj
      
    - solution_folder: VS/Lesson_dz_one/Lesson_dz_one/
      full_project_name: VS/Lesson_dz_one/Lesson_dz_one/Lesson_dz_one.csproj 
    
    - solution_folder: VS/Infestation/Infestation/
      full_project_name: VS/Infestation/Infestation/Infestation.csproj  

    - solution_folder: /VS/Fortune/
      full_project_name: /VS/Fortune/Fortune.csproj  

before_build: nuget restore %solution_folder%
build: 
    project: '%full_project_name%'
    publish_wap: true