version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore
    build matrix: 
        -project: \VS\News_Table\News_Table\News_Table.csproj     
         publish_wap: true
        -project: \VS\Lesson_dz_one\Lesson_dz_one\Lesson_dz_one.csproj    
         publish_wap: true
        -project: \VS\Infestation\Infestation\Infestation.csproj     
         publish_wap: true
       
 