version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore
    -build: 
        project: 
            -\VS\News_Table\News_Table\News_Table.csproj
            -\VS\Lesson_dz_one\Lesson_dz_one\Lesson_dz_one.csproj
            -\VS\Infestation\Infestation\Infestation.csproj
            -\VS\Fortune\Fortune.csproj
        publish_wap: true